export const TAMIL_NADU_LOCATIONS: Record<string, string[]> = {
  Chennai: [
    "All",

    // Key Belts
    "OMR",
    "ECR",
    "GST Road",
    "Radial Road 200ft",

    // A
    "Adambakkam",
    "Adyar",
    "Agaram",
    "Agaram Then",
    "Agaramel",
    "Akkarai",
    "Alandur",
    "Alapakkam",
    "Alwarpet",
    "Alwarthirunagar",
    "Ambattur",
    "Ambattur Estate",
    "Ambattur Industrial Estate",
    "Aminjikarai",
    "Anakaputhur",
    "Anna Nagar",
    "Anna Nagar East",
    "Anna Nagar West",
    "Anna Nagar West Extension",
    "Anna Salai",
    "Annanur",
    "Arakkonam",
    "Arumbakkam",
    "Ashok Nagar",
    "Athipattu",
    "Athipattu Pudunagar",
    "Avadi",
    "Avadi IAF",
    "Ayanambakkam",
    "Ayanavaram",
    "Ayappakkam",

    // B
    "Banaveduthottam",
    "Besant Nagar",
    "Bharathipuram",
    "Boat Club",
    "Broadway",

    // C
    "Cathedral Road",
    "Chembarambakkam",
    "Chengalpattu",
    "Chepauk",
    "Chetpet",
    "Chettipedu",
    "Chettipunyam",
    "Chinmaya Nagar",
    "Chinnasekkadu",
    "Chintadripet",
    "Chitlapakkam",
    "Choolai",
    "Choolaimedu",
    "Chromepet",
    "CIT Nagar",

    // E
    "East Coast Road",
    "Egattur",
    "Egmore",
    "Ennore",
    "Ernavur",

    // G
    "George Town",
    "Gerugambakkam",
    "Gopalapuram",
    "Gowrivakkam",
    "Guduvancheri",
    "Gummidipoondi",
    "Guindy",

    // H
    "Hasthinapuram",

    // I
    "IIT Madras Area",
    "Injambakkam",
    "Irumbuliyur",
    "Iyyappanthangal",

    // J
    "Jafferkhanpet",
    "Jamalia",

    // K
    "K K Nagar",
    "Kadambathur",
    "Kadappakkam",
    "Kaladipet",
    "Kalakshetra Colony",
    "Kallikuppam",
    "Kancheepuram",
    "Kandanchavadi",
    "Karambakkam",
    "Karapakkam",
    "Karayanchavadi",
    "Karunakaracheri",
    "Kattankulathur",
    "Kattupakkam",
    "Kattur",
    "Keelkattalai",
    "Kelambakkam",
    "Kil Ayanambakkam",
    "Kilpauk",
    "Kodambakkam",
    "Kodungaiyur",
    "Kolappancheri",
    "Kolathur",
    "Korattur",
    "Korukkupet",
    "Kosapet",
    "Kottivakkam",
    "Kottur",
    "Kotturpuram",
    "Kovalam",
    "Kovilambakkam",
    "Kovilpathagai",
    "Koyambedu",
    "Kundrathur",
    "Kuthambakkam",

    // M
    "Madhavaram",
    "Madhavaram Milk Colony",
    "Madipakkam",
    "Maduravoyal",
    "Mahabalipuram",
    "Mamallapuram",
    "Mahindra World City",
    "Manali",
    "Manali New Town",
    "Manapakkam",
    "Mandaveli",
    "Mangadu",
    "Mannadi",
    "Mannivakkam",
    "Maraimalai Nagar",
    "Medavakkam",
    "Meenambakkam",
    "Meppur",
    "Mettukuppam",
    "Mevalurkuppam",
    "Minjur",
    "Mogappair",
    "Mogappair East",
    "Mogappair West",
    "Moolacheri",
    "Moolakadai",
    "Morai",
    "MRC Nagar",
    "Mudichur",
    "Mugalivakkam",
    "Muttukadu",
    "Mylapore",

    // N
    "Nadukuthagai",
    "Nallambakkam",
    "Nandambakkam",
    "Nandanam",
    "Nandivaram",
    "Nandivaram-Guduvancheri",
    "Nanganallur",
    "Nanmangalam",
    "Navalur",
    "Nazarathpet",
    "Neelankarai",
    "Nemilicheri",
    "Nerkundram",
    "Nesapakkam",
    "New Washermenpet",
    "Nolambur",
    "Nungambakkam",

    // O
    "Old Washermenpet",
    "Oragadam",
    "Otteri",

    // P
    "Padi",
    "Padappai",
    "Padur",
    "Pakkam",
    "Palavedu",
    "Palavakkam",
    "Pallavaram",
    "Pallikaranai",
    "Pammal",
    "Panaiyur",
    "Paranur",
    "Parivakkam",
    "Park Town",
    "Parrys Corner",
    "Pattabiram",
    "Pattinapakkam",
    "Pazhavanthangal",
    "Peerkankaranai",
    "Perambakkam",
    "Perambur",
    "Peravallur",
    "Periamet",
    "Perumbakkam",
    "Perungalathur",
    "Perungudi",
    "Polichalur",
    "Ponneri",
    "Ponniammanmedu",
    "Poonamallee",
    "Porur",
    "Potheri",
    "Pudupakkam",
    "Pudupet",
    "Pulianthope",
    "Purasaiwakkam",
    "Puzhal",
    "Puzhuthivakkam",

    // R
    "R A Puram",
    "Rajakilpakkam",
    "Ramapuram",
    "Red Hills",
    "Retteri",
    "Royapettah",
    "Royapuram",

    // S
    "Saidapet",
    "Saligramam",
    "Santhome",
    "Selaiyur",
    "Sembakkam",
    "Senneerkuppam",
    "Shenoy Nagar",
    "Sholavaram",
    "Sholinganallur",
    "Singaperumal Koil",
    "Siruseri",
    "Sithalapakkam",
    "Sowcarpet",
    "Sriperumbudur",
    "St. Thomas Mount",
    "Surapet",

    // T
    "T Nagar",
    "Tambaram",
    "Tambaram East",
    "Tambaram West",
    "Taramani",
    "Teynampet",
    "Thalambur",
    "Thandalam",
    "Thirumangalam",
    "Thirumazhisai",
    "Thirumudivakkam",
    "Thirumullaivoyal",
    "Thiruneermalai",
    "Thiruninravur",
    "Thiruporur",
    "Thiruvallur",
    "Thiruverkadu",
    "Thiruvanmiyur",
    "Thiruvottiyur",
    "Thoraipakkam",
    "Thousand Lights",
    "Tiruttani",
    "Tondiarpet",
    "Triplicane",

    // U
    "Urapakkam",
    "Uthandi",

    // V
    "Vadapalani",
    "Valasaravakkam",
    "Vandalur",
    "Varadarajapuram",
    "Velachery",
    "Vellanur",
    "Vengaivasal",
    "Veppampattu",
    "Vettuvankani",
    "Villivakkam",
    "Virugambakkam",
    "Vyasarpadi",

    // W
    "Washermenpet",
    "West Mambalam",

    // Z
    "Zamin Pallavaram"
  ],

  Coimbatore: ["All", "Gandhipuram", "Peelamedu", "RS Puram", "Saibaba Colony", "Vadavalli", "Saravanampatti"],
  Madurai: ["All", "Anna Nagar", "K.Pudur", "KK Nagar", "Simmakkal", "Sellur"],
  Trichy: ["All", "Thillai Nagar", "Woraiyur", "Srirangam", "K.K. Nagar"],
  Salem: ["All", "Fairlands", "Hasthampatti", "Alagapuram", "Suramangalam"],
  Vellore: ["All", "Sathuvachari", "Katpadi", "Gandhinagar", "Arcot Road"],
  Erode: ["All", "Perundurai Road", "Thindal", "Sampath Nagar"],
  Tiruppur: ["All", "Avinashi Road", "Palladam Road", "Rayapuram"],
  Tirunelveli: ["All", "Palayamkottai", "Maharaja Nagar", "Perumalpuram"],
  Thanjavur: ["All", "Medical College Road", "NK Road", "Pattukottai Road"],
  Thoothukudi: ["All", "Millerpuram", "Chidambara Nagar", "Meelavittan"],
  Nagercoil: ["All", "Kottar", "Vadasery", "Parvathipuram"],
  Hosur: ["All", "Zuzuvadi", "Mookandapalli", "Mathigiri"],
  Kanchipuram: ["All", "Orikkai", "Little Kanchipuram", "Ennaikaran"],
  Dindigul: ["All", "Palani Road", "Natham Road", "Batlagundu Road"],
  Karur: ["All", "Gandhigramam", "Thanthonimalai", "Vengamedu"],
  Kumbakonam: ["All", "TSR Big Street", "Sakkottai", "Darasuram"],
  Sivakasi: ["All", "Sattur Road", "Virudhunagar Road", "Thiruthangal"]
};

export const TAMIL_NADU_CITIES = Object.keys(TAMIL_NADU_LOCATIONS);