export const TAMIL_NADU_LOCATIONS: Record<string, string[]> = {
  Chennai: [
    "All",

    // Key Belts
    "OMR",
    "ECR",
    "GST Road",
    "Radial Road 200ft",

    // A
    "Adambakkam",
    "Adyar",
    "Agaram",
    "Agaram Then",
    "Agaramel",
    "Akkarai",
    "Alandur",
    "Alapakkam",
    "Alwarpet",
    "Alwarthirunagar",
    "Ambattur",
    "Ambattur Estate",
    "Ambattur Industrial Estate",
    "Aminjikarai",
    "Anakaputhur",
    "Anna Nagar",
    "Anna Nagar East",
    "Anna Nagar West",
    "Anna Nagar West Extension",
    "Anna Salai",
    "Annanur",
    "Arakkonam",
    "Arumbakkam",
    "Ashok Nagar",
    "Athipattu",
    "Athipattu Pudunagar",
    "Avadi",
    "Avadi IAF",
    "Ayanambakkam",
    "Ayanavaram",
    "Ayappakkam",

    // B
    "Banaveduthottam",
    "Besant Nagar",
    "Bharathipuram",
    "Boat Club",
    "Broadway",

    // C
    "Cathedral Road",
    "Chembarambakkam",
    "Chengalpattu",
    "Chepauk",
    "Chetpet",
    "Chettipedu",
    "Chettipunyam",
    "Chinmaya Nagar",
    "Chinnasekkadu",
    "Chintadripet",
    "Chitlapakkam",
    "Choolai",
    "Choolaimedu",
    "Chromepet",
    "CIT Nagar",

    // E
    "East Coast Road",
    "Egattur",
    "Egmore",
    "Ennore",
    "Ernavur",

    // G
    "George Town",
    "Gerugambakkam",
    "Gopalapuram",
    "Gowrivakkam",
    "Guduvancheri",
    "Gummidipoondi",
    "Guindy",

    // H
    "Hasthinapuram",

    // I
    "IIT Madras Area",
    "Injambakkam",
    "Irumbuliyur",
    "Iyyappanthangal",

    // J
    "Jafferkhanpet",
    "Jamalia",

    // K
    "K K Nagar",
    "Kadambathur",
    "Kadappakkam",
    "Kaladipet",
    "Kalakshetra Colony",
    "Kallikuppam",
    "Kancheepuram",
    "Kandanchavadi",
    "Karambakkam",
    "Karapakkam",
    "Karayanchavadi",
    "Karunakaracheri",
    "Kattankulathur",
    "Kattupakkam",
    "Kattur",
    "Keelkattalai",
    "Kelambakkam",
    "Kil Ayanambakkam",
    "Kilpauk",
    "Kodambakkam",
    "Kodungaiyur",
    "Kolappancheri",
    "Kolathur",
    "Korattur",
    "Korukkupet",
    "Kosapet",
    "Kottivakkam",
    "Kottur",
    "Kotturpuram",
    "Kovalam",
    "Kovilambakkam",
    "Kovilpathagai",
    "Koyambedu",
    "Kundrathur",
    "Kuthambakkam",

    // M
    "Madhavaram",
    "Madhavaram Milk Colony",
    "Madipakkam",
    "Maduravoyal",
    "Mahabalipuram",
    "Mamallapuram",
    "Mahindra World City",
    "Manali",
    "Manali New Town",
    "Manapakkam",
    "Mandaveli",
    "Mangadu",
    "Mannadi",
    "Mannivakkam",
    "Maraimalai Nagar",
    "Medavakkam",
    "Meenambakkam",
    "Meppur",
    "Mettukuppam",
    "Mevalurkuppam",
    "Minjur",
    "Mogappair",
    "Mogappair East",
    "Mogappair West",
    "Moolacheri",
    "Moolakadai",
    "Morai",
    "MRC Nagar",
    "Mudichur",
    "Mugalivakkam",
    "Muttukadu",
    "Mylapore",

    // N
    "Nadukuthagai",
    "Nallambakkam",
    "Nandambakkam",
    "Nandanam",
    "Nandivaram",
    "Nandivaram-Guduvancheri",
    "Nanganallur",
    "Nanmangalam",
    "Navalur",
    "Nazarathpet",
    "Neelankarai",
    "Nemilicheri",
    "Nerkundram",
    "Nesapakkam",
    "New Washermenpet",
    "Nolambur",
    "Nungambakkam",

    // O
    "Old Washermenpet",
    "Oragadam",
    "Otteri",

    // P
    "Padi",
    "Padappai",
    "Padur",
    "Pakkam",
    "Palavedu",
    "Palavakkam",
    "Pallavaram",
    "Pallikaranai",
    "Pammal",
    "Panaiyur",
    "Paranur",
    "Parivakkam",
    "Park Town",
    "Parrys Corner",
    "Pattabiram",
    "Pattinapakkam",
    "Pazhavanthangal",
    "Peerkankaranai",
    "Perambakkam",
    "Perambur",
    "Peravallur",
    "Periamet",
    "Perumbakkam",
    "Perungalathur",
    "Perungudi",
    "Polichalur",
    "Ponneri",
    "Ponniammanmedu",
    "Poonamallee",
    "Porur",
    "Potheri",
    "Pudupakkam",
    "Pudupet",
    "Pulianthope",
    "Purasaiwakkam",
    "Puzhal",
    "Puzhuthivakkam",

    // R
    "R A Puram",
    "Rajakilpakkam",
    "Ramapuram",
    "Red Hills",
    "Retteri",
    "Royapettah",
    "Royapuram",

    // S
    "Saidapet",
    "Saligramam",
    "Santhome",
    "Selaiyur",
    "Sembakkam",
    "Senneerkuppam",
    "Shenoy Nagar",
    "Sholavaram",
    "Sholinganallur",
    "Singaperumal Koil",
    "Siruseri",
    "Sithalapakkam",
    "Sowcarpet",
    "Sriperumbudur",
    "St. Thomas Mount",
    "Surapet",

    // T
    "T Nagar",
    "Tambaram",
    "Tambaram East",
    "Tambaram West",
    "Taramani",
    "Teynampet",
    "Thalambur",
    "Thandalam",
    "Thirumangalam",
    "Thirumazhisai",
    "Thirumudivakkam",
    "Thirumullaivoyal",
    "Thiruneermalai",
    "Thiruninravur",
    "Thiruporur",
    "Thiruvallur",
    "Thiruverkadu",
    "Thiruvanmiyur",
    "Thiruvottiyur",
    "Thoraipakkam",
    "Thousand Lights",
    "Tiruttani",
    "Tondiarpet",
    "Triplicane",

    // U
    "Urapakkam",
    "Uthandi",

    // V
    "Vadapalani",
    "Valasaravakkam",
    "Vandalur",
    "Varadarajapuram",
    "Velachery",
    "Vellanur",
    "Vengaivasal",
    "Veppampattu",
    "Vettuvankani",
    "Villivakkam",
    "Virugambakkam",
    "Vyasarpadi",

    // W
    "Washermenpet",
    "West Mambalam",

    // Z
    "Zamin Pallavaram"
  ],

  Coimbatore: ["All", "Avinashi Road", "Bharathiyar Road", "Cheran Ma Nagar", "Ganapathy", "Gandhipuram", "Kalapatti", "Kovaipudur", "Kurichi", "Lakshmi Mills", "Neelambur", "Ondipudur", "Peelamedu", "Podanur", "Race Course", "Ramanathapuram", "RS Puram", "Saibaba Colony", "Saravanampatti", "Singanallur", "Sundarapuram", "Thudiyalur", "Ukkadam", "Vadavalli", "Vellalore", "Vilimedu"],
  Madurai: ["All", "Anna Nagar", "Arappalayam", "Avaniyapuram", "Bypass Road", "Ellis Nagar", "Iyer Bungalow", "K.Pudur", "KK Nagar", "Mattuthavani", "Nagamalai Pudukottai", "Othakadai", "Pasumalai", "Sellur", "Simmakkal", "Tallakulam", "Thirunagar", "Villapuram"],
  Trichy: ["All", "Cantonment", "Crawford", "Edamalaipatti Pudur", "K.K. Nagar", "Karumandapam", "Kattur", "Manachanallur", "Puthur", "Samayapuram", "Srirangam", "Thillai Nagar", "Thiruverumbur", "Thuvakudi", "Woraiyur"],
  Salem: ["All", "Alagapuram", "Ammapet", "Fairlands", "Five Roads", "Gugai", "Hasthampatti", "Kondalampatti", "Seelanaickenpatti", "Shevapet", "Suramangalam", "Yercaud Road"],
  Vellore: ["All", "Arcot Road", "Bagayam", "Gandhinagar", "Katpadi", "Sathuvachari", "Thorapadi", "Viruthampet"],
  Erode: ["All", "Karungalpalayam", "Kollampalayam", "Perundurai Road", "Sampath Nagar", "Solar", "Surampatti", "Thindal", "Veerappanchatram"],
  Tiruppur: ["All", "Anupparpalayam", "Avinashi Road", "Chettipalayam", "Murugampalayam", "Nallur", "Palladam Road", "PN Road", "Rayapuram", "Velampalayam"],
  Tirunelveli: ["All", "Melapalayam", "Maharaja Nagar", "Palayamkottai", "Perumalpuram", "Pettai", "Thatchanallur", "Vannarpettai"],
  Thanjavur: ["All", "Anna Nagar", "East Main Street", "Medical College Road", "NK Road", "Pattukottai Road", "Pillaiyarpatti", "Rahman Nagar", "Vallam"],
  Thoothukudi: ["All", "Bryant Nagar", "Chidambara Nagar", "Korampallam", "Meelavittan", "Millerpuram", "Muthiahpuram", "Toovipuram"],
  Nagercoil: ["All", "Asaripallam", "Kottar", "Nesamony Nagar", "Parvathipuram", "Suchindram", "Vadasery", "Vetturnimadam"],
  Hosur: ["All", "Bagalur Road", "Hosur New Town", "Mathigiri", "Mookandapalli", "Shanthi Nagar", "Zuzuvadi"],
  Kanchipuram: ["All", "Ennaikaran", "Kalimedu", "Little Kanchipuram", "Orikkai", "Pillaiyarpalayam", "Sevilimedu"],
  Dindigul: ["All", "Batlagundu Road", "Begampur", "Natham Road", "Palani Road", "RM Colony", "Siluvathur Road"],
  Karur: ["All", "Gandhigramam", "Jawahar Bazaar", "Pasupathipalayam", "Ramanujam Nagar", "Thanthonimalai", "Vengamedu"],
  Kumbakonam: ["All", "Darasuram", "Koranattu Karuppur", "Sakkottai", "Swamimalai", "TSR Big Street", "Valayapettai"],
  Sivakasi: ["All", "Reserve Line", "Sattur Road", "Sivakasi East", "Thiruthangal", "Virudhunagar Road"]
};

export const TAMIL_NADU_CITIES = Object.keys(TAMIL_NADU_LOCATIONS);
